defaults:
  - _self_

hydra:
  run:
    dir: output/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}

base:
  dim: 2

fluid:
  Re: 100.0          # Fluid density [kg/m³]

time:
  dt: 0.01           # Time step size [s]
  t_end: 10.0       # Final simulation time [s]

mesh:
  filepath: mesh/rectangle_p1.msh  # Path to GMSH mesh file
  deg_u: 1
  deg_p: 1

boundary:
  dirichlet:
    velocity:
      - [9, "uniform", 0, 1.0]   # [tag, type, dir, value]
      - [9, "uniform", 1, 0.0]
      - [10, "uniform", 0, 0.0]
      - [10, "uniform", 1, 0.0]
    pressure:
      - [12, 0.0]

solver:
  output_interval: 1

