defaults:
  - _self_

hydra:
  run:
    dir: output/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}

base:
  dim: 2

fluid:
  Re: 200.0

time:
  dt: 0.01
  t_end: 50

mesh:
  filepath: mesh/cylinder_p2.msh  # Path to GMSH file
  deg_u: 2
  deg_p: 1

boundary:
  dirichlet:
    velocity:  # [tag, type, dir, value]
      # - [9, "uniform", 0, 1.0]
      # - [9, "uniform", 1, 0.0]
      # - [10, "uniform", 0, 0.0]   
      # - [10, "uniform", 1, 0.0]
      - [1, "uniform", 0, 1.0]
      - [1, "uniform", 1, 0.0]
      - [3, "uniform", 1, 0.0]   
      - [4, "uniform", 1, 0.0]
      - [5, "uniform", 0, 0.0]
      - [5, "uniform", 1, 0.0]
    pressure:
      - [2, 0.0]

solver:
  output_interval: 10

