defaults:
  - _self_

hydra:
  job:
    name: straight_tube_with_womersley_flow
  run:
    dir: output/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}

base:
  dim: 2

fluid:
  U: 1.0
  L: 0.5
  rho: 200
  mu: 1.0

time:
  dt: 0.005
  t_end: 50

mesh:
  filepath: mesh/straight_tube.msh  # Path to GMSH file
  deg_u: 2
  deg_p: 1

boundary:
  dirichlet:
    velocity:  # [tag, type, dir, value]
      - [9, "uniform", 0, 0.0]
      - [9, "uniform", 1, 0.0]
      - [10, "uniform", 0, 0.0]
      - [10, "uniform", 1, 0.0]
    poiseuille:
      # if none, don't specify
      radius: 0.5
      center: [-4, 0]
      normal: [1,  0]
    pressure:
      - [6, "pulsatile", 0.0]
      - [8, "constant", 0.0]

solver:
  output_interval: 10

